#!/usr/bin/env bash
source 001-Variaveis.sh

EMPRESA=SYSTEC

Logo_Empresa () {
	clear
	echo ""
	echo -e " \e[1;31m =================================================================== \e[m ";
	figlet -c "$EMPRESA"
	echo -e " \e[1;31m =================================================================== \e[m ";
	echo ""
	echo ""
	return
}

_Comparar_String () {
	Logo_Empresa
		local Var1=$_String_a_Comparar
		local Var2=$_Minha_Escrita

		while [ ["$Var1" != "$Var2" ] ]; do
			if [ "$?" = "0" ] ; then
				Logo_Empresa
				echo "TEVE UM ERRO NA ESCRITA"
				echo "VAMOS TENTAR DE NOVO"
				echo -e '\e[34;1;3m' "$_String_a_Comparar \e[m";
				read nuevo
				Var2=$nuevo
			fi
		done 
}

_Obtendo_Informacoes () {
	Logo_Empresa
	echo ""
	echo -e '\e[36;3m' "AGORA VAMOS IDENTIFICAR A INTERFACE FISICA DA REDE    \e[m";
	echo "------------------------------------------------------------- "
	echo -e '\e[36;3m' "DIGITA: \e[m";
	echo -e '\e[36;3m' "sudo lshw -class network | grep logical name \e[m"; 
		read _Minha_Escrita
		_String_a_Comparar="sudo lshw -class network | grep logical name"
		_Comparar_String

	Logo_Empresa		
	echo -e '\e[36;3m' "DIGITA A INTEFACE ONDE O SERVIDOR VAI ESTAR CONECTADO    \e[m";
		sudo lshw -class network | grep "logical name"
		echo "------------------------------------------------------------- "
		echo ""
		read _INTERFACE_LAN
	
	Logo_Empresa
	echo ""
	echo -e '\e[36;3m' "DIGITA O IP FIXO DESTE SERVIDOR ?    \e[m";
	echo "------------------------------------------------------------- "
	echo ""
	read _IP_STATIC
	
	Logo_Empresa
	echo ""
	echo -e '\e[36;3m' " QUAL É A NETMASK DE REDE ( EX. 255.255.255.0) ?   \e[m";
	echo "------------------------------------------------------------- "
	echo ""
	read _MASCARA

	Logo_Empresa
	echo ""
	echo -e '\e[36;3m' " QUAL É O NETWORK DA REDE ( EX. XXX.XXX.X.0) ?   \e[m";
	echo "------------------------------------------------------------- "
	echo ""
	read _NETWORK
	
	Logo_Empresa
	echo ""
	echo -e '\e[36;3m' " QUAL É O SEU GATEWAY ?  (O MESMO DO FIREWALL)  \e[m";
	echo "------------------------------------------------------------- "
	echo ""
	read _GATEWAY
		
	Logo_Empresa
	echo ""
	echo -e '\e[36;3m' " QUAL É O NOME DO SERVIDOR   \e[m";
	echo "------------------------------------------------------------- "
	echo ""
	read _NOME_SERVIDOR
	
	Logo_Empresa
	echo ""
	echo -e '\e[36;3m' " QUAL É O NOME DO DOMINIO-FQDN (EX. EXEMPLO.COM.BRZ   \e[m";
	echo "------------------------------------------------------------- "
	echo ""
	read _NOME_DOMINIO_FQDN
	
	Logo_Empresa
	echo ""
	echo -e '\e[36;3m' " QUAL É O NOME DO NETBIOS DO DOMINIO (EX. EXEMPLO   \e[m";
	echo "------------------------------------------------------------- "
	echo ""
	read _NOME_DOMINIO_NETBIOS
	
}

clear
echo -e "carregando..."
DEBIAN_FRONTEND=noninteractive
export DEBIAN_FRONTEND
EMPRESA=SYSTEC
	pacote=$(dpkg --get-selections | grep "figlet" )
		if [ -n "$pacote" ] ;then
			echo
		else
			apt-get install figlet -qq > /dev/null
		fi

	clear
		Logo_Empresa
			echo "VAMOS PRECISAR INFORMAÇOES BASICAS -- (s/n)"
			echo ""
			echo ""
			read RESPOSTA
				if [ $RESPOSTA = "s" ] ; then
					_Obtendo_Informacoes
				fi

	clear
	Logo_Empresa
	echo ""
	echo -e "CONFIRA AS INFORMACOES POR FAVOR"
	echo "------------------------------------------------------------- "
	echo ""
	echo ""
	
	echo -e '\e[36;3m' " IP DO SERVIDOR:  		\e[m" 			$_IP_STATIC
	echo -e '\e[36;3m' " MASCARA DE REDE:  		\e[m" 			$_MASCARA
	echo -e '\e[36;3m' " NETWORK DE REDE:  		\e[m" 			$_NETWORK
	echo -e '\e[36;3m' " GATEWAY DA REDE:  		\e[m" 			$_GATEWAY
	echo -e '\e[36;3m' " INTERFACE NA SWITCH:	\e[m" 			$_INTERFACE_LAN
	echo -e '\e[36;3m' " NOME DO SERVIDOR: 		\e[m" 			$_NOME_SERVIDOR
	echo -e '\e[36;3m' " NOME DO DOMINIO:  		\e[m" 			$_NOME_DOMINIO_FQDN
	echo -e '\e[36;3m' " NOME NETBIOS:   		\e[m"			$_NOME_DOMINIO_NETBIOS
	echo ""
	echo ""
	echo "------------------------------------------------------------- "
	echo ""
	echo -e "AS INFORMACOES ESTAO CORRETAS ? S/N" 
	echo ""
		read 
	
	touch /Ubuntu20.04/Scripts/001-Variaveis.sh
		cat << EOF > /Ubuntu20.04/Scripts/001-Variaveis.sh
			_IP_STATIC=$_IP_STATIC
			_MASCARA=$_MASCARA
			_NETWORK=$_NETWORK
			_GATEWAY=$_GATEWAY
			_INTERFACE_LAN=$_INTERFACE_LAN
			_NOME_SERVIDOR=$_NOME_SERVIDOR
			_NOME_DOMINIO_FQDN=$_NOME_DOMINIO_FQDN
			_NOME_DOMINIO_NETBIOS=$_NOME_DOMINIO_NETBIOS
EOF

exit